### PR TITLE
Feature 1

### PR DESCRIPTION
**Pull request by Namrata-J**
#1 added avatar component
Please review it, thankyou!!

### CODE REVIEW

**Comment by ShreyashMahajan** [comment]
the name of the components was easy and recognizable, which is a very good thing. On line number 171 of the Avatar style component instead of "r", you can write rounded ( just a suggestion).

**Review by tushartiwari7 — APPROVED** [review]
code is clear and understandable. Also Nice commit messages
You can merge this. 👍

**Comment by Namrata-J** [comment]
> the name of the components was easy and recognizable, which is a very good thing. On line number 171 of the Avatar style component instead of "r", you can write rounded ( just a suggestion).

Thankyou!! so much for the suggestion will look definitely look into it.

**Comment by Namrata-J** [comment]
> code is clear and understandable. Also Nice commit messages You can merge this. 👍

thankyou so much for reviewing!!

**Comment by SuyashTiwariCoder** [comment]
Code looks good , you can merge

**Pull request merged**
